### ISSUE TITLE
The new admin view doesn't show admin/statistics.html page

### ISSUE THREAD

**Issue by sathish-sperentes** [duplxey/django-interactive-charts#4]
http://127.0.0.1:8000/admin/statistics/ - new admin view
Followed your wonderful tutorial and came across an issue with this particular view.  It doesn't show admin/statistics.html page instead gives 404 error.

Page not found (404)
Request Method: | GET
Request URL: http://127.0.0.1:8000/admin/statistics
Raised by: django.contrib.admin.sites.catch_all_view

Using the URLconf defined in core.urls, Django tried these URL patterns, in this order:
    admin/ [name='index']
    admin/ login/ [name='login']
    admin/ logout/ [name='logout']
    admin/ password_change/ [name='password_change']
    admin/ password_change/done/ [name='password_change_done']
    admin/ autocomplete/ [name='autocomplete']
    admin/ jsi18n/ [name='jsi18n']
    admin/ r/<int:content_type_id>/<path:object_id>/ [name='view_on_site']
    admin/ auth/group/
    admin/ auth/user/
    admin/ shop/item/
    admin/ shop/purchase/
    admin/ ^(?P<app_label>auth|shop)/$ [name='app_list']
    admin/ (?P<url>.*)$

The current path, admin/statistics, matched the last one.

**Comment by duplxey** [comment]
I cloned the repository and everything works well, I think there's a problem on your side.

I'm closing the issue, feel free to reopen the issue if the problem persists.
