### ISSUE TITLE
ModuleNotFoundError: No module named 'pytz'

### ISSUE THREAD

**Issue by EncryptEx** [duplxey/django-interactive-charts#7]
When performing the db_populate command, an error occurs even though I've just installed all dependencies. 
Solved the issue by doing: 
`pip install pytz`

I'd recommend adding the pytz package to the requirements.txt file.

**Comment by duplxey** [comment]
Good catch @EncryptEx. Fixed in #7ad50f6.

**Comment by duplxey** [comment]
Good catch @EncryptEx. Fixed in #7ad50f6.

**Comment by duplxey** [comment]
Good catch @EncryptEx. I added `pytz` to *requirements.txt* in the latest commit.
